# Generated by Django 5.0.7 on 2024-07-29 14:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog_application', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='bloguser',
            name='is_staff',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='bloguser',
            name='is_superuser',
            field=models.BooleanField(default=False),
        ),
    ]
