# Generated by Django 5.0.7 on 2024-07-29 16:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog_application', '0004_tag_blogpost_like'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blogpost',
            name='search_vector',
        ),
    ]
