# Generated by Django 5.0.7 on 2024-07-30 02:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog_application', '0005_remove_blogpost_search_vector'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blogpost',
            name='author',
        ),
    ]
